version: '3'

services:
  # Laravel service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "9000:9000"

  # React service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: react_app
    networks:
      - app-network
    depends_on:
      - app
    ports:
      - "3000:3000"

  # MySQL service
  db:
    image: mysql:8.3
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: btb
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    command: --skip-ssl
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: 123456
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
